apiVersion: batch/v1
kind: CronJob
metadata:
  name: payday-batch-verifi
spec:
  schedule: "0 */1 * * *"
  #schedule: "*/3 * * * *"

  # ジョブを同時実行するかどうか
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 6
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
            - name: payday-batch-verifi
              image: curlimages/curl:latest
              args:
                - /bin/sh
                - -c
                - "curl -X POST http://payday-batch-verifi.payday-batch.svc.cluster.local:3000/payslip/bulkinsert"
          restartPolicy: OnFailure
